/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-tertiary-fixed-variant": "#7d2d00",
              "tertiary-container": "#bc4800",
              "surface": "#f7f9fb",
              "inverse-primary": "#b4c5ff",
              "on-primary-fixed-variant": "#003ea8",
              "error": "#ba1a1a",
              "on-tertiary-fixed": "#360f00",
              "on-secondary-fixed-variant": "#38485d",
              "on-error": "#ffffff",
              "surface-tint": "#0053db",
              "primary-fixed-dim": "#b4c5ff",
              "on-surface-variant": "#434655",
              "surface-container": "#eceef0",
              "primary-fixed": "#dbe1ff",
              "background": "#f7f9fb",
              "tertiary-fixed-dim": "#ffb596",
              "on-primary": "#ffffff",
              "outline": "#737686",
              "outline-variant": "#c3c6d7",
              "on-secondary-container": "#54647a",
              "inverse-surface": "#2d3133",
              "secondary-fixed": "#d3e4fe",
              "surface-dim": "#d8dadc",
              "secondary-container": "#d0e1fb",
              "tertiary-fixed": "#ffdbcd",
              "error-container": "#ffdad6",
              "surface-container-low": "#f2f4f6",
              "secondary-fixed-dim": "#b7c8e1",
              "surface-container-lowest": "#ffffff",
              "on-primary-container": "#eeefff",
              "on-surface": "#191c1e",
              "surface-variant": "#e0e3e5",
              "surface-container-highest": "#e0e3e5",
              "on-background": "#191c1e",
              "on-error-container": "#93000a",
              "secondary": "#505f76",
              "primary": "#004ac6",
              "tertiary": "#943700",
              "surface-container-high": "#e6e8ea",
              "on-secondary": "#ffffff",
              "surface-bright": "#f7f9fb",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed": "#0b1c30",
              "inverse-on-surface": "#eff1f3",
              "primary-container": "#2563eb",
              "on-primary-fixed": "#00174b",
              "on-tertiary-container": "#ffede6"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "gutter": "16px",
              "base": "4px",
              "container-padding": "24px",
              "component-internal-sm": "8px",
              "component-internal-md": "12px",
              "section-gap": "48px"
          },
          "fontFamily": {
              "label-caps": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-xl": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "button": ["Inter", "sans-serif"]
          },
          "fontSize": {
              "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg": ["30px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-xl": ["36px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "button": ["14px", {"lineHeight": "20px", "fontWeight": "500"}]
          }
      },
  },
  plugins: [],
}
